apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-training-root-e2e
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ml-training
  source:
    repoURL: https://github.com/rashesh91/ml-training-platform.git
    targetRevision: HEAD
    path: argocd-config/apps-e2e
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
